# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b47f3325d57233feb52503580d08b919cd85f84eef8a9e57fa97dbd01c56f05bbf33ccb02c7bf6f0880e5331840d67d8ec185e3e9e6020b7486d623088a0237

test:
  secret_key_base: fe16693e91534cd1a2cba9e4cc50ae3e8addc02897d57a64c616b00f9ac2908d6ee8363b27f5c7afb14a5d68fb13b2094b94f9991e777f33685c643446da6eb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
